# Generated by Django 4.2.7 on 2024-11-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзины', 'verbose_name_plural': 'Корзины'},
        ),
    ]
